/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_Data4jni */

#ifndef _Included_codebase_Data4jni
#define _Included_codebase_Data4jni
#ifdef __cplusplus
extern "C" {
#endif
#undef codebase_Data4jni_LOCKALL
#define codebase_Data4jni_LOCKALL -1L
#undef codebase_Data4jni_LOCKAPPEND
#define codebase_Data4jni_LOCKAPPEND -2L
#undef codebase_Data4jni_LOCKFILE
#define codebase_Data4jni_LOCKFILE -3L
/*
 * Class:     codebase_Data4jni
 * Method:    fieldType
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_codebase_Data4jni_fieldType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    fieldNumber
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_fieldNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    fieldLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_fieldLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    fieldDecimals
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_fieldDecimals
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    aliasJ
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_codebase_Data4jni_aliasJ__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    aliasJ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_aliasJ__
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    appendJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_appendJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    appendStartJ
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_appendStartJ
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     codebase_Data4jni
 * Method:    bottomJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_bottomJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    closeJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_closeJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    compressJ
 * Signature: (Lcodebase/Data4jni;Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_codebase_Data4jni_compressJ
  (JNIEnv *, jobject, jobject, jstring, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    createJ
 * Signature: (Ljava/lang/String;[Lcodebase/Field4define;[Lcodebase/Tag4define;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_Data4jni_createJ
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

/*
 * Class:     codebase_Data4jni
 * Method:    i4create
 * Signature: (Ljava/lang/String;[Lcodebase/Tag4define;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_i4create
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     codebase_Data4jni
 * Method:    getNumFields
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_getNumFields
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    getFieldName
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_getFieldName
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    getFieldType
 * Signature: (S)C
 */
JNIEXPORT jchar JNICALL Java_codebase_Data4jni_getFieldType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    getFieldLen
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_getFieldLen
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    getFieldDec
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_getFieldDec
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    getFieldNull
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_getFieldNull
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    goJ
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_goJ
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_Data4jni
 * Method:    lockAddJ
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_lockAddJ
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_Data4jni
 * Method:    memoCompressJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_memoCompressJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    openJ
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_Data4jni_openJ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    openIndexJ
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_openIndexJ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    packJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_packJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    positionJ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_codebase_Data4jni_positionJ__
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    positionJ
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_positionJ__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     codebase_Data4jni
 * Method:    recCountJ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_recCountJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    recNoJ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_codebase_Data4jni_recNoJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    refreshRecordJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_refreshRecordJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    reindexJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_reindexJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    seekJ
 * Signature: (D)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_seekJ__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     codebase_Data4jni
 * Method:    seekJ
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_seekJ__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    seekJ
 * Signature: ([B)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_seekJ___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     codebase_Data4jni
 * Method:    seekNextJ
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_seekNextJ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    seekUnicodeJ
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_seekUnicodeJ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    selectJ
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_selectJ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    skipJ
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_skipJ
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_Data4jni
 * Method:    tagRemove
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_codebase_Data4jni_tagRemove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    topJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_topJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    flushJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_flushJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    f4null
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_f4null__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4null
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_f4null__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assignNull
 * Signature: (Ljava/lang/String;)V
 */
// LY Jul 5/04 : removed __Ljava_lang_String_2 from end of function name
JNIEXPORT void JNICALL Java_codebase_Data4jni_f4assignNull
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assignNull
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_codebase_Data4jni_f4assignNull__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4binary
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_codebase_Data4jni_f4binary__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4binary
 * Signature: (Ljava/lang/String;)[B
 */
// LY Jul 5/04 removed __S from end of function name
JNIEXPORT jbyteArray JNICALL Java_codebase_Data4jni_f4binary
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    deleteJ
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_deleteJ__
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (Ljava/lang/String;[B)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__Ljava_lang_String_2_3B
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (S[B)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__S_3B
  (JNIEnv *, jobject, jshort, jbyteArray);

/*
 * Class:     codebase_Data4jni
 * Method:    deleteJ
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_deleteJ__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     codebase_Data4jni
 * Method:    f4double
 * Signature: (Ljava/lang/String;)D
 */
// LY Jul 5/04 : removed __Ljava_lang_String_2 from end of function name
JNIEXPORT jdouble JNICALL Java_codebase_Data4jni_f4double
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4double
 * Signature: (S)D
 */
JNIEXPORT jdouble JNICALL Java_codebase_Data4jni_f4double__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (Ljava/lang/String;D)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (SD)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__SD
  (JNIEnv *, jobject, jshort, jdouble);

/*
 * Class:     codebase_Data4jni
 * Method:    f4boolean
 * Signature: (Ljava/lang/String;)Z
 */
// LY Jul 5/05 : removed __Ljava_lang_String_2 from end of function name
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_f4boolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4boolean
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_codebase_Data4jni_f4boolean__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (Ljava/lang/String;Z)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (SZ)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__SZ
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     codebase_Data4jni
 * Method:    f4str
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
// LY Jul 5/04 : removed __Ljava_lang_String_2 from end of function name
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_f4str
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4str
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_f4str__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assign
 * Signature: (SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assign__SLjava_lang_String_2
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4strUnicode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
// LY Jul 5/04 : removed __Ljava_lang_String_2 from end of function name
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_f4strUnicode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4strUnicode
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Data4jni_f4strUnicode__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assignUnicode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
// LY Jul 5/05 : removed __Ljava_lang_String_2Ljava_lang_String_2 from end of function name
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assignUnicode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     codebase_Data4jni
 * Method:    f4assignUnicode
 * Signature: (SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_Data4jni_f4assignUnicode__SLjava_lang_String_2
  (JNIEnv *, jobject, jshort, jstring);

#ifdef __cplusplus
}
#endif
#endif
