/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_File4jni */

#ifndef _Included_codebase_File4jni
#define _Included_codebase_File4jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codebase_File4jni
 * Method:    file4close
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4close
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4compressCreate
 * Signature: (Lcodebase/File4jni;Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4jni_file4compressCreate
  (JNIEnv *, jobject, jobject, jstring, jshort);

/*
 * Class:     codebase_File4jni
 * Method:    file4compressOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4jni_file4compressOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_File4jni
 * Method:    file4create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4jni_file4create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_File4jni
 * Method:    file4flush
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4flush
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4isValid
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4isValid
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4len
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_codebase_File4jni_file4len
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4lenSet
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4lenSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_File4jni
 * Method:    file4lock
 * Signature: (II)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4lock
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     codebase_File4jni
 * Method:    file4name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_File4jni_file4name
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4jni_file4open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     codebase_File4jni
 * Method:    file4optimize
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4optimize
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     codebase_File4jni
 * Method:    file4optimizeWrite
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4optimizeWrite
  (JNIEnv *, jobject, jshort);

/*
 * Class:     codebase_File4jni
 * Method:    file4read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_codebase_File4jni_file4read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     codebase_File4jni
 * Method:    file4readAll
 * Signature: (I[BI)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4readAll
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     codebase_File4jni
 * Method:    file4refresh
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4refresh
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4replace
 * Signature: (Lcodebase/File4jni;)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4replace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     codebase_File4jni
 * Method:    file4unlock
 * Signature: (II)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4unlock
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     codebase_File4jni
 * Method:    file4write
 * Signature: (I[BI)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4jni_file4write
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
