/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_File4seqReadJni */

#ifndef _Included_codebase_File4seqReadJni
#define _Included_codebase_File4seqReadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codebase_File4seqReadJni
 * Method:    file4seqRead
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_codebase_File4seqReadJni_file4seqRead
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     codebase_File4seqReadJni
 * Method:    file4seqReadAll
 * Signature: ([BI)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4seqReadJni_file4seqReadAll
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     codebase_File4seqReadJni
 * Method:    file4seqReadBufferAlloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4seqReadJni_file4seqReadBufferAlloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_File4seqReadJni
 * Method:    file4seqReadFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_codebase_File4seqReadJni_file4seqReadFree
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4seqReadJni
 * Method:    file4seqReadInit
 * Signature: (Lcodebase/File4jni;II)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4seqReadJni_file4seqReadInit
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
