/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_Tag4jni */

#ifndef _Included_codebase_Tag4jni
#define _Included_codebase_Tag4jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codebase_Tag4jni
 * Method:    d4tagJ
 * Signature: (Lcodebase/Data4jni;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_Tag4jni_d4tagJ
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     codebase_Tag4jni
 * Method:    t4exprJ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Tag4jni_t4exprJ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
