/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_File4seqWriteJni */

#ifndef _Included_codebase_File4seqWriteJni
#define _Included_codebase_File4seqWriteJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWrite
 * Signature: ([BI)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4seqWriteJni_file4seqWrite
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWriteBufferAlloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4seqWriteJni_file4seqWriteBufferAlloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWriteFlush
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4seqWriteJni_file4seqWriteFlush
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWriteFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_codebase_File4seqWriteJni_file4seqWriteFree
  (JNIEnv *, jobject);

/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWriteInit
 * Signature: (Lcodebase/File4jni;II)J
 */
JNIEXPORT jlong JNICALL Java_codebase_File4seqWriteJni_file4seqWriteInit
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     codebase_File4seqWriteJni
 * Method:    file4seqWriteRepeat
 * Signature: (IB)S
 */
JNIEXPORT jshort JNICALL Java_codebase_File4seqWriteJni_file4seqWriteRepeat
  (JNIEnv *, jobject, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
