/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codebase_Expr4jni */

#ifndef _Included_codebase_Expr4jni
#define _Included_codebase_Expr4jni
#ifdef __cplusplus
extern "C" {
#endif
#undef codebase_Expr4jni_DATE
#define codebase_Expr4jni_DATE 68L
#undef codebase_Expr4jni_DATEDOUB
#define codebase_Expr4jni_DATEDOUB 100L
#undef codebase_Expr4jni_LOG
#define codebase_Expr4jni_LOG 76L
#undef codebase_Expr4jni_NUM
#define codebase_Expr4jni_NUM 78L
#undef codebase_Expr4jni_NUMDOUB
#define codebase_Expr4jni_NUMDOUB 110L
#undef codebase_Expr4jni_STR
#define codebase_Expr4jni_STR 67L
/*
 * Class:     codebase_Expr4jni
 * Method:    expr4doubleJ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_codebase_Expr4jni_expr4doubleJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4freeJ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_codebase_Expr4jni_expr4freeJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4isNullJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Expr4jni_expr4isNullJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4lenJ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_codebase_Expr4jni_expr4lenJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4parseJ
 * Signature: (Lcodebase/Data4jni;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_codebase_Expr4jni_expr4parseJ
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4sourceJ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Expr4jni_expr4sourceJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4strJ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_codebase_Expr4jni_expr4strJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4trueJ
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_codebase_Expr4jni_expr4trueJ
  (JNIEnv *, jobject);

/*
 * Class:     codebase_Expr4jni
 * Method:    expr4typeJ
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_codebase_Expr4jni_expr4typeJ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
